services:
  doc:
    build:
      context: ./doc
      dockerfile: Dockerfile
    platform: linux/amd64
    command: sleep infinity
    volumes:
      - type: bind
        source: ./doc
        target: /workspace/doc
  dev:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /workspace/function-ddd-sample
    # コンテナが常時動作するようなコマンド、ここでは例として sleep を利用
    command: sleep infinity
